version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/transfer_jobs
    docker:
      - image: circleci/ruby:2.4.1-node
      - image: redis:3.2.7

    steps:
      - checkout

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Run rspec in parallel
      - run: |
          rake test

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
